
import type { Metadata } from "next";
import { Providers } from "@/store/Providers";
import { Footer, Header, SideBarLayout } from "@/components/layout";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <Providers>
      <SideBarLayout>
        {children}
      </SideBarLayout>
    </Providers>

  );
}
